# Site wide configuration

title:            Sven Amann
tagline:          Software Quality Consultant
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:           en_US
timezone:         DE
url:              http://sven-amann.de


# Jekyll configuration

permalink:   /:categories/:year/:month/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false


# Site owner
owner:
  name: Sven Amann
  avatar: bio-photo.jpg # 160x160 px image for author byline
  bio: ""
  email: info@sven-amann.de
  disqus-shortname: svenamann
  twitter: svamann
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: salsolatragus
  stackoverflow: 1372671/sven
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: letsdeveloper
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username


collections:
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", vendor, "serve-dev.sh"]
