#!/usr/bin/env bash
set -e # halt script on error

bundle install
bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external --allow-hash-href --url-swap "https?\:\/\/(127\.0\.0\.1\:4000|localhost\:4000|sven-amann\.de):" --check-html

apt-get install ncftp
ncftpput -R -v -u "$FTP_USER" -p "$FTP_PASS" w00952b3.kasserver.com / ./_site/*
